# .github/workflows/sync-my-fork.yml

name: Sync My Fork from Upstream

on:
  schedule:
    # 每小时运行一次，自动检查更新
    - cron: '0 * * * *'
  workflow_dispatch:
    # 允许你手动点击按钮触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Fork
        uses: actions/checkout@v4
        with:
          # 使用 GITHUB_TOKEN，它具有推送到你 Fork 的权限
          persist-credentials: false
          # 获取所有历史记录，避免合并问题
          fetch-depth: 0

      - name: Add Upstream Remote
        run: |
          # 将这里的 UPSTREAM_USERNAME/UPSTREAM_REPONAME 替换成原作者的用户名和仓库名！
          git remote add upstream https://github.com/perfect-panel/ppanel-web.git

      - name: Fetch from Upstream
        run: git fetch upstream

      - name: Merge Upstream Changes
        run: |
          # 确保你在正确的分支上，通常是 main
          git checkout main
          git merge upstream/main --ff-only

      - name: Push changes to Fork
        run: git push origin main
